/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 20 02:59:47 GMT 2018
 */

package com.uepb.tcc.gildedrose.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.uepb.tcc.gildedrose.GildedRose;
import com.uepb.tcc.gildedrose.Item;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GildedRose_ESTest extends GildedRose_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Item[] itemArray0 = new Item[8];
      Item item0 = new Item("e:(L!Ud.U${P&n>oZfR", (-31), (-653));
      itemArray0[0] = item0;
      itemArray0[1] = item0;
      itemArray0[2] = item0;
      itemArray0[3] = itemArray0[2];
      itemArray0[4] = itemArray0[3];
      itemArray0[5] = itemArray0[2];
      Item item1 = new Item("Entrada para os Bastidores", 3481, (-31));
      itemArray0[6] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.atualizaQualidade();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Item[] itemArray0 = new Item[6];
      Item item0 = new Item("", (-1), (-1363));
      itemArray0[0] = item0;
      itemArray0[1] = itemArray0[0];
      itemArray0[2] = item0;
      Item item1 = new Item("Entrada para os Bastidores", (-1), 50);
      itemArray0[3] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.atualizaQualidade();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Item[] itemArray0 = new Item[6];
      Item item0 = new Item("", (-1), (-1363));
      itemArray0[0] = item0;
      itemArray0[1] = item0;
      Item item1 = new Item("", 1285, 0);
      itemArray0[2] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.atualizaQualidade();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Item[] itemArray0 = new Item[7];
      Item item0 = new Item("Brie Envelhecido", 1892, 1892);
      itemArray0[0] = item0;
      itemArray0[1] = item0;
      itemArray0[2] = item0;
      itemArray0[3] = item0;
      Item item1 = new Item("Brie Envelhecido", 0, 1892);
      itemArray0[4] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.atualizaQualidade();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Item[] itemArray0 = new Item[5];
      Item item0 = new Item("Sulfuras", 2953, 2953);
      itemArray0[0] = item0;
      itemArray0[1] = itemArray0[0];
      Item item1 = new Item("Sulfuras", (-1340), 2953);
      itemArray0[2] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.atualizaQualidade();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Item[] itemArray0 = new Item[5];
      Item item0 = new Item("AtwbWA", (-635), (-1));
      itemArray0[0] = item0;
      itemArray0[1] = itemArray0[0];
      itemArray0[2] = item0;
      Item item1 = new Item("Entrada para os Bastidores", 11, (-635));
      itemArray0[3] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.atualizaQualidade();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Item[] itemArray0 = new Item[5];
      Item item0 = new Item("AtwbWA", (-635), (-1));
      itemArray0[0] = item0;
      itemArray0[1] = itemArray0[0];
      itemArray0[2] = item0;
      itemArray0[3] = itemArray0[1];
      Item item1 = new Item("Entrada para os Bastidores", (-3190), 968);
      itemArray0[4] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      gildedRose0.atualizaQualidade();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Item[] itemArray0 = new Item[5];
      Item item0 = new Item("AtwbWA", (-635), (-1));
      itemArray0[0] = item0;
      itemArray0[1] = item0;
      Item item1 = new Item("J!A*DIFlW:W=.}", (-635), 1290);
      itemArray0[2] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.atualizaQualidade();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Item[] itemArray0 = new Item[5];
      Item item0 = new Item("AtwbWA", (-635), (-1));
      itemArray0[0] = item0;
      Item item1 = new Item("Entrada para os Bastidores", (-1), (-635));
      itemArray0[1] = item1;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.atualizaQualidade();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.gildedrose.GildedRose", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Item[] itemArray0 = new Item[16];
      Item item0 = new Item("Brie Envelhecido", 0, 1);
      itemArray0[0] = item0;
      GildedRose gildedRose0 = new GildedRose(itemArray0);
      // Undeclared exception!
      try { 
        gildedRose0.atualizaQualidade();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uepb.tcc.gildedrose.GildedRose", e);
      }
  }
}
